'use client'

import Link from 'next/link'
import LegalPage from '@/sections/legal/LegalPage'

const sections = ({ siteName, contactLink }) => [
    {
        id: 'acceptance',
        title: 'Agreement to these terms',
        body: (
            <p>
                These Terms of Service govern your use of {siteName}. By creating an account or using the service you agree to
                these terms and to our <Link href="/privacy">Privacy Policy</Link>. If you do not agree, please do not use {siteName}.
            </p>
        ),
    },
    {
        id: 'educational-use',
        title: 'Educational use only — not medical advice',
        body: (
            <>
                <p>
                    {siteName} is a study aid for students. Answers are generated by artificial intelligence and may be incomplete,
                    out of date or incorrect. They are <strong>not medical advice</strong> and must not be used to diagnose, treat or
                    make decisions about real patients.
                </p>
                <p>Always verify important information against your course materials, instructors, preceptors and current clinical guidelines.</p>
            </>
        ),
    },
    {
        id: 'accounts',
        title: 'Your account',
        body: (
            <ul>
                <li>You must be at least 16 years old and provide accurate information when you sign up.</li>
                <li>You are responsible for keeping your password secure and for all activity on your account.</li>
                <li>Accounts are personal — do not share your login with others.</li>
            </ul>
        ),
    },
    {
        id: 'acceptable-use',
        title: 'Acceptable use',
        body: (
            <>
                <p>When using {siteName}, you agree not to:</p>
                <ul>
                    <li>Enter information that identifies a real patient, or any other confidential health information.</li>
                    <li>Use the service for anything unlawful, harmful, harassing or deceptive.</li>
                    <li>Attempt to disrupt, overload, reverse-engineer or gain unauthorized access to the service.</li>
                    <li>Use automated tools to scrape the service or resell access to it.</li>
                </ul>
            </>
        ),
    },
    {
        id: 'plans-payments',
        title: 'Plans and payments',
        body: (
            <ul>
                <li>Paid plans cover one month of access and include a monthly token allowance shown at checkout.</li>
                <li><strong>Plans do not renew automatically.</strong> When your month ends, chat pauses until you purchase another month.</li>
                <li>Tokens measure usage. If you use your full allowance before the month ends, you can upgrade or start a new month.</li>
                <li>Prices are shown before you pay and processed securely by Stripe. If you believe you were charged in error, contact us via {contactLink}.</li>
            </ul>
        ),
    },
    {
        id: 'cancellation',
        title: 'Cancellation and termination',
        body: (
            <>
                <p>You can cancel your plan at any time from Settings → Plan &amp; usage. Cancelling stops chat access for the current plan; because plans never renew, you can also simply let your month run out.</p>
                <p>We may suspend or close accounts that violate these terms or put the service or other users at risk.</p>
            </>
        ),
    },
    {
        id: 'content',
        title: 'Your content and our service',
        body: (
            <p>
                You keep ownership of the questions and materials you submit, and you give us permission to process them to
                provide the service. The {siteName} software, design and branding belong to us and our licensors.
            </p>
        ),
    },
    {
        id: 'availability',
        title: 'Availability and changes',
        body: (
            <p>We work to keep {siteName} available and accurate, but the service is provided &quot;as is&quot; and may occasionally be unavailable for maintenance or reasons outside our control. We may add, change or remove features over time.</p>
        ),
    },
    {
        id: 'liability',
        title: 'Limitation of liability',
        body: (
            <p>
                To the fullest extent permitted by law, {siteName} is not liable for indirect or consequential losses, or for any
                decisions made based on AI-generated content. Our total liability for any claim relating to the service is limited
                to the amount you paid us in the month before the claim arose. Nothing in these terms limits rights you have under
                consumer protection law that cannot be excluded.
            </p>
        ),
    },
    {
        id: 'changes',
        title: 'Changes to these terms',
        body: <p>We may update these terms from time to time. We will update the date at the top of this page, and continued use of {siteName} after changes take effect means you accept the updated terms.</p>,
    },
    {
        id: 'contact',
        title: 'Contact us',
        body: <p>Questions about these terms? Reach us via {contactLink}.</p>,
    },
]

export default function TermsContent() {
    return (
        <LegalPage
            current="/terms"
            title="Terms of Service"
            intro={({ siteName }) => `The rules for using ${siteName}. Please read them carefully.`}
            sections={sections}
        />
    )
}
